[project]
name = "catalog-matcher"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.128.0",
    "openai>=2.16.0",
    "pandas>=3.0.0",
    "pydantic>=2.12.5",
]
